# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [197]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [198]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
df = pd.read_csv(url, sep=("|"))

In [199]:
df.info()
# zip code look like it can convert to int, but after more checking it contains also char's.

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [200]:
df.describe(include="all")

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

In [201]:
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. Discover what is the mean age per occupation

In [202]:
df.groupby("occupation")["age"].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [203]:
# Finne hvor mange det er av hvert gender i hver occuption. Fylle alle rader med transform. Count for å ikke telle NaN
# df.groupby(["occupation", "gender"])["gender"].transform("count")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [204]:
# # Finne hvor mange det er totalt gender i hver occuption. Fylle alle rader med transform. Count for å ikke telle NaN
# df.groupby(["occupation"])["gender"].transform("count")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [205]:
# Locate M gender i dataframe, hente ut kolonnene gender, occuptaion og ratio, droppe doble føringen grunnet transform, sortere høyest først.
by_gender = df.groupby(["occupation", "gender"])["gender"].transform("count")
total = df.groupby(["occupation"])["gender"].transform("count")
df["ratio_m_%"] = (by_gender / total) * 100
df.loc[
    df["gender"] == "M",
       ["occupation","ratio_m_%"]] \
        .drop_duplicates() \
            .sort_values(by="ratio_m_%", ascending=False)

        occupation   ratio_m_%
137         doctor  100.000000
24        engineer   97.014925
0       technician   96.296296
105        retired   92.857143
16      programmer   90.909091
5        executive   90.625000
13       scientist   90.322581
15   entertainment   88.888889
9           lawyer   83.333333
111       salesman   75.000000
12        educator   72.631579
8          student   69.387755
82           other   65.714286
46       marketing   61.538462
2           writer   57.777778
56            none   55.555556
6    administrator   54.430380
30          artist   53.571429
18       librarian   43.137255
59      healthcare   31.250000
897      homemaker   14.285714

In [206]:
# # sjekke repo løsning. Like denne.

# def gender_to_numeric(x):
#     if x == 'M':
#         return 1
#     if x == 'F':
#         return 0

# # # apply the function to the gender column and create a new column
# df['gender_n'] = df['gender'].apply(gender_to_numeric)
# df

In [207]:
# # Sjekke repoløsning. Like denne.
# a = df.groupby('occupation').gender_n.sum() / df.occupation.value_counts() * 100 
# a.sort_values(ascending=False)

### Step 6. For each occupation, calculate the minimum and maximum ages

In [208]:
df.groupby(["occupation"])["age"].agg(["min", "max"]).sort_values(by="max", ascending=False)

               min  max
occupation
retired         51   73
administrator   21   70
engineer        22   70
executive       22   69
librarian       23   69
salesman        18   66
other           13   64
doctor          28   64
educator        23   63
programmer      20   63
healthcare      22   62
writer          18   60
marketing       24   55
none            11   55
scientist       23   55
technician      21   55
lawyer          21   53
entertainment   15   50
homemaker       20   50
artist          19   48
student          7   42

### Step 7. For each combination of occupation and gender, calculate the mean age

In [ ]:
# Bruker named aggregation for penere oversikt da dette gir DataFrame og ikke series.
# Jeg synes dette er penere når jeg bygger en summary table
df.groupby(["occupation", "gender",]).agg(mean_age = ("age", "mean"))

                       mean_age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

In [252]:
prct_df = df.groupby("occupation").agg(
    prct_women=("gender", lambda x: (x=='F').mean()*100),
    prct_male=("gender", lambda x: (x=='M').mean()*100),
).round(2)

prct_df["check_sum"] = prct_df["prct_women"] + prct_df["prct_male"]

# prct_df
prct_df.drop("check_sum", axis=1)

               prct_women  prct_male
occupation
administrator       45.57      54.43
artist              46.43      53.57
doctor               0.00     100.00
educator            27.37      72.63
engineer             2.99      97.01
entertainment       11.11      88.89
executive            9.38      90.62
healthcare          68.75      31.25
homemaker           85.71      14.29
lawyer              16.67      83.33
librarian           56.86      43.14
marketing           38.46      61.54
none                44.44      55.56
other               34.29      65.71
programmer           9.09      90.91
retired              7.14      92.86
salesman            25.00      75.00
scientist            9.68      90.32
student             30.61      69.39
technician           3.70      96.30
writer              42.22      57.78

In [249]:
(prct_df["prct_women"] + prct_df["prct_male"]).eq(100).all()

np.True_