# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

### Step 4. See the first 10 entries

In [3]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [4]:
# Solution 1
chipo["order_id"].count().sum()

np.int64(4622)

In [5]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [6]:
# Solution 2
chipo.shape

(4622, 5)

### Step 6. What is the number of columns in the dataset?

In [7]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [8]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

### Step 8. How is the dataset indexed?

In [9]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [27]:
# Viser med antall
# best_item = chipo[["item_name", "quantity"]].groupby("item_name").sum().sort_values("quantity", ascending=False).head(1) 

# Uten antall som dataframe, huske å resette index da groupby gjør item_name til index
# best_item = chipo[["item_name", "quantity"]].groupby("item_name").sum().sort_values("quantity", ascending=False).head(1).reset_index()
# best_item[["item_name"]]

# Bruke index og første row for å hente ut item_name som string
best_item = chipo[["item_name", "quantity"]].groupby("item_name").sum().sort_values("quantity", ascending=False).head(1)
best_item[["item_name"]]

KeyError: "None of [Index(['item_name'], dtype='str')] are in the [columns]"

### Step 10. For the most-ordered item, how many items were ordered?

In [11]:
best_item[["quantity"]]

              quantity
item_name
Chicken Bowl       761

### Step 11. What was the most ordered item in the choice_description column?

In [12]:
chipo.groupby("choice_description")["quantity"].sum().idxmax()
total_orders = chipo

### Step 12. How many items were orderd in total?

In [13]:
chipo[["quantity"]].sum()

quantity    4972
dtype: int64

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [14]:
chipo.dtypes["item_price"]

#### Step 13.b. Create a lambda function and change the type of item price

In [15]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "").astype(float)

#### Step 13.c. Check the item price type

In [16]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

### Step 14. How much was the revenue for the period in the dataset?

In [17]:
chipo["revenue"] = chipo["quantity"] * chipo["item_price"]
total = chipo["revenue"].sum()
print(f"Total revenue was ${total:,.2f}".replace(",", " "))

Total revenue was $39 237.02

### Step 15. How many orders were made in the period?

In [18]:
chipo["quantity"].sum()

np.int64(4972)

### Step 16. What is the average revenue amount per order?

In [19]:
# Solution 1

In [20]:
# Solution 2

### Step 17. How many different items are sold?